### PR TITLE
Cleanup

### PR DESCRIPTION
**Pull request by abandohess**

### CODE REVIEW

**Comment by abandohess** [comment]
This code sucks

**Comment by jcheong0428** [comment]
Hey @abandohess, thanks for the pull request. 
We could certainly add you to the team list, but can you position yourself next to Teddy or Jane to keep the row style consistent?  Also would be nice to add Anne Muller too if you have the chance as she contributed much of the design too. We could also consider transposing the order so that cosan lab is one row and the dali lab are another row if it gets too crowded. 

As for cleaning up the graphics, we also initially tested the empty canvas version as you committed but ended up going with the app-like version to be consistent with the iOS app. Also we were on a time crunch to launch so the javascript code is not the most elegant. Would be awesome if you could refactor it to be more manageable and scalable across mobile/web platforms since you might be most familiar with web dev amongst us. Thanks again!

**Comment by abandohess** [comment]
Hey @jcheong0428 I just messaged Anne so she can pick a photo of herself and tell me what she wants the photo to link to. I'll create a new PR when I get that back. I'll also take a look at the javascript

**Comment by Teddarific** [comment]
@abandohess Let me know if Anne doesn't get back to ya, and I can probably dig up an old DALI photo.

**Pull request closed without merging**
